# Generated by Django 5.0.2 on 2024-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Hematologist', 'Hematologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Rheumatologist', 'Rheumatologist'), ('Urologist', 'Urologist'), ('Other', 'Other')], default='Cardiologist', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
